Participate/config/routes.rb
Rails.application.routes.draw do

  root 'application#index'
  resources :shapes, :only => [:index,:edit,:update] do
    collection do
      get :reset
    end
  end

  resources :steps, :only => [:index] do
    collection do
      post :set
      put :set
      get :reset
    end
  end

end

Participate/app/models/drum.rb
class Drum < ActiveRecord::Base

  # has_many :steps

  def Drum.register(name)
    drum = Drum.find_by_name(name)
    if drum
      puts "Drum already exists: #{name}"
    else
      Drum.create(:name => name)
    end
  end



end

Participate/app/models/shape.rb
class Shape < ActiveRecord::Base

  POS_OPTS = [
    5,
    10,
    15,
    20,
    25,
    30,
    35,
    40,
    45,
    50,
    55,
    60,
    65,
    70,
    75,
    80,
    85,
    90,
    95,
    100
  ]

  SIZE_OPTS = [
    0.1,
    0.2,
    0.3,
    0.4,
    0.5,
    0.6,
    0.7,
    0.8,
    0.9,
    1
  ]

  scope :active, lambda{where(:active => true).order('name asc')}
  scope :inactive, lambda{where(:active => [false,nil]).order('name asc')}


  cattr_accessor :pd_connect

  def Shape.pd_connect
    return @@pd_connect if @@pd_connect
    @@pd_connect = UDPSocket.new
    @@pd_connect.connect('localhost', 9595)
    @@pd_connect
  end

  def Shape.send_message(message)
    Shape.pd_connect.send("#{message};\n",0)
  end

  # places shape on the board by passing a message to pd
  #
  # shape name xpos ypos size
  # shape test 50 50 0.2
  #
  def pass
    Shape.send_message("shape #{name} #{xpos} #{ypos} #{size}")
    update_attribute :passed, true
  end

  def Shape.register(name)
    if Shape.find_by_name(name)
      puts "Shape already exists: #{name}"
    else
      s = Shape.new(
        :name => name,
        :xpos => 50,
        :ypos => 50,
        :size => 0.5
      )
      s.save!
    end
  rescue => er
    puts "Couldn't register shape: #{name}"
    puts er.message
    puts er.backtrace
  end

  def randomise
    self.xpos = Shape::POS_OPTS[rand(Shape::POS_OPTS.size)]
    self.ypos = Shape::POS_OPTS[rand(Shape::POS_OPTS.size)]
    self.size = Shape::SIZE_OPTS[rand(Shape::SIZE_OPTS.size)]
  end

end

Participate/app/models/step.rb
class Step < ActiveRecord::Base

  belongs_to :drum

  def Step.register(position)
    step = Step.find_by_position(position)
    if step
      step
    else
      Step.create(
        :position => position,
        :drum_id => Drum.find_by_name('none').try(:id)
      )
    end
  end

  cattr_accessor :pd_connect

  def pd_connect
    Shape.pd_connect
  end

  def play
    Shape.send_message("drum #{self.drum.name}")
  end

end

Participate/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @shapes = Shape.inactive.all
    @drums = Drum.all
    @steps = Step.order('position asc').all
  end
end

Participate/app/controllers/shapes_controller.rb
class ShapesController < ApplicationController

  before_action :get_shape, :only => [:edit, :update]

  def edit
    @shape.randomise
    @shape.active = true
    @shape.passed = false
  end

  def update
    if @shape.update_attributes(shape_params)
      flash[:notice] = 'Shape has been added'
    else
      flash[:error] = 'Something went wrong, oops'
    end
    redirect_to shapes_path
  end

  def reset
    Shape.all.each{|x|x.update_attribute :active, :false}
    Shape.send_message('reset-game 1')
    redirect_to shapes_path
  end

  protected

  def get_shape
    @shape = Shape.find(params[:id])
  end

  def shape_params
    params.require(:shape).permit(:name, :xpos, :ypos, :size, :active,:passed)
  end

end

Participate/app/controllers/steps_controller.rb
class StepsController < ApplicationController

  def set
    step=Step.find(params[:id])
    step.drum_id = params[:drum_id]
    step.save
  end

  def reset
    blank_drum = Drum.find_by_name('none')
    Step.connection.execute("update steps set drum_id = #{blank_drum.id};")
  end

end

Participate/app/helpers/application_helper.rb
module ApplicationHelper
end

Participate/app/helpers/shapes_helper.rb
module ShapesHelper
end

Participate/app/views/application/index.html.erb
<h1>Audience Participation Stuff!</h1>

Participate/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Participate</title>
  <%= stylesheet_link_tag 'application', 'bootstrap.min', 'slider', media: 'all',  'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'bootstrap.min', 'bootstrap-slider', 'data-turbolinks-track' => true %>
  <%= %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
</head>
<body>

<% if flash[:notice] and !flash[:notice].blank? %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>

<% if flash[:error] and !flash[:error].blank? %>
  <div class="alert alert-error" role="alert"><%= flash[:error] %></div>
<% end %>

<ul>
  <li><%= link_to 'shapes', shapes_path %></li>
  <li><%= link_to 'drums', steps_path %></li>
  <li><%= link_to 'reset game', reset_shapes_path %></li>
</ul>


<%= yield %>

</body>
</html>

Participate/app/views/shapes/edit.html.erb
<h1>Placing Shape: <%= @shape.name %></h1>

<%= form_for @shape do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, :disabled => true %>
  </div>

  <div class="form-group">
    <%= form.label :xpos %>
    <input type="text" class="span2" value="<%= @shape.xpos%>"
           id="xpos" name="shape[xpos]"
           data-slider-min="0" data-slider-max="100"
           data-slider-step="1" data-slider-value="<%= @shape.xpos %>"
           data-slider-orientation="vertcal"
           data-slider-selection="after" data-slider-tooltip="hide">
    <%#= form.select(
          :xpos,
          options_for_select(
            Shape::POS_OPTS,
            :selected => @shape.xpos
          )
    ) %>
  </div>

  <div class="form-group">
    <%= form.label :ypos %>
    <input type="text" class="span2" value="<%= @shape.ypos%>"
           id="ypos" name="shape[ypos]"
           data-slider-min="0" data-slider-max="100"
           data-slider-step="1" data-slider-value="<%= @shape.ypos %>"
           data-slider-orientation="vertical"
           data-slider-selection="after" data-slider-tooltip="hide">
    <%#= form.select(
          :ypos,
          options_for_select(
            Shape::POS_OPTS,
            :selected => @shape.ypos
          )
        ) %>
  </div>

  <div class="form-group">
    <%= form.label :size%>
    <input type="text" class="span2" value="<%= @shape.size%>"
           id="size" name="shape[size]"
           data-slider-min="0" data-slider-max="1"
           data-slider-step="0.05" data-slider-value="<%= @shape.size %>"
           data-slider-selection="after" data-slider-tooltip="hide">
    <%#= form.select(
          :size,
          options_for_select(
            Shape::SIZE_OPTS,
            :selected => @shape.size
          )
        ) %>
  </div>

  <%= form.hidden_field :active %>
  <%= form.hidden_field :passed %>


  <%= form.submit 'Place Shape', :class=> 'btn btn-default' %>

<% end %>

<script type=text/javascript>
  $('#xpos').slider();
  $('#ypos').slider();
  $('#size').slider();

</script>

Participate/app/views/shapes/index.html.erb
<h2>Shapes:</h2>

<%= link_to "Reset Shapes", reset_shapes_path, :confirm => "Do not do this unless you're Andrew!" %>

<% if @shapes.any? %>
  <ul>
    <% @shapes.each do |shape| %>
      <li><%= link_to shape.name, edit_shape_path(shape) %></li>
    <% end %>
  </ul>
<% else %>
  <p>It looks like all the shapes are already on the board</p>
<% end %>

Participate/app/views/steps/index.html.erb
<h2>Drums</h2>
<%= link_to "reset", "#", :id => 'reset_link' %>
<table class='table table-bordered' id="drum-table">
  <thead>
  <tr>
    <th></th>
    <% @steps.each do |step| %>
      <th><%= step.position %></th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% @drums.each do |drum| %>
    <tr>
      <th><%= drum.name %></th>
      <% @steps.each do |step| %>
        <td class='step-choose <%= 'success' if step.drum == drum %>'
            id="<%= step.id %>" drum_id='<%= drum.id %>'></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>

</table>

<script type="text/javascript">

  $('#reset_link').on('click', function() {
    $.get('/steps/reset');
    $('#drum-table tr td').removeClass('active');
    $('#drum-table tr:last td').addClass('active');
  });

  $('.step-choose').on('click', function () {
    var columnNo = $(this).index();
    $(this).closest("table").find("tr td:nth-child(" + (columnNo+1) + ")").removeClass('success');
    $(this).addClass('success');
    $.post(
      '/steps/set',
      {
        id: $(this).attr("id"),
        drum_id: $(this).attr('drum_id')
      }
    )
  });
</script>